/*
 * Decompiled with CFR 0.152.
 */
package com.rumilance.practice.gui;

public enum GuiType {
    RANKED_QUEUE,
    UNRANKED_QUEUE,
    DUEL_REQUEST,
    DUEL_MAP,
    KIT_SELECT,
    PLAYERS,
    SETTINGS,
    SPECTATE_LIST,
    STATS_KIT,
    EDIT_KIT,
    ORIGINAL_KIT,
    FFA_LIST,
    ARROW_EFFECT,
    ADMIN_MENU,
    KIT_ADMIN,
    PROFILE,
    EKIT_SELECT,
    EKIT_EDIT,
    EKIT_CHOICE,
    EKIT_COPY,
    CONFIRM,
    ENCHANT,
    POTION,
    EKIT_ADMIN,
    GAME_MENU,
    BATTLE_MENU,
    BOT_MENU,
    TITLE_SELECT,
    KIT_PREVIEW,
    MATCH_REPORT,
    MATCH_INVENTORY,
    TEAMS_BROWSER,
    TEAM_HUB,
    TEAM_KIT_SELECT,
    BAN_LIST,
    REPORT,
    REPORT_LIST,
    PRESET_ADMIN;

}
