name: publish-resourcepack

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload resource pack to the release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload v1.76.45 dist/RumilanceResourcePack.zip --repo "$GITHUB_REPOSITORY" --clobber
